In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import lxml

In [3]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1', headers=headers).text

In [4]:
soup=BeautifulSoup(webpage,'html.parser')

In [5]:
company= soup.find_all('div',class_='companyCardWrapper')

In [6]:
len(company)

20

In [7]:
name=[]
rating=[]
review=[]

In [8]:
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div', attrs={'style': 'height:auto;padding-bottom:1px;'}).text.strip())
    review.append(i.find('span',class_='companyCardWrapper__ActionCount').text.strip())

In [9]:
d={'name':name, 'rating':rating, 'review':review}

In [10]:
df= pd.DataFrame(d)

In [11]:
df

                      name rating review
0                      TCS    3.4   1.1L
1                Accenture    3.7    68k
2                    Wipro    3.7  60.9k
3                Cognizant    3.7  57.9k
4                Capgemini    3.7  49.6k
5                HDFC Bank    3.8    48k
6                  Infosys    3.5  45.5k
7               ICICI Bank    4.0  43.7k
8                  HCLTech    3.4  42.6k
9            Tech Mahindra    3.4  40.8k
10                 Genpact    3.6  39.1k
11         Teleperformance    3.8    35k
12               Axis Bank    3.7  30.9k
13  Concentrix Corporation    3.6  30.4k
14                     Jio    4.3  29.7k
15                  Amazon    4.0  29.4k
16              iEnergizer    4.6  26.9k
17         Reliance Retail    3.9    26k
18                     IBM    3.9  24.6k
19             LTIMindtree    3.6  24.2k

In [14]:
final=pd.DataFrame()

for j in range(1,11):
    url='https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
    webpage=requests.get(url, headers=headers).text

    soup=BeautifulSoup(webpage,'html.parser')

    company= soup.find_all('div',class_='companyCardWrapper')

    name=[]
    rating=[]
    review=[]

    for i in company:
        name.append(i.find('h2').text.strip())
        rating.append(i.find('div', attrs={'style': 'height:auto;padding-bottom:1px;'}).text.strip())
        review.append(i.find('span',class_='companyCardWrapper__ActionCount').text.strip())

    d={'name':name, 'rating':rating, 'review':review}

    df=pd.DataFrame(d)
    final=pd.concat([final, df], ignore_index=True)

In [15]:
final

                    name rating review
0                    TCS    3.4   1.1L
1              Accenture    3.7    68k
2                  Wipro    3.7  60.9k
3              Cognizant    3.7  57.9k
4              Capgemini    3.7  49.6k
..                   ...    ...    ...
195     Publicis Sapient    3.4   3.6k
196               Subros    3.8   3.6k
197     American Express    4.1   3.6k
198              Viatris    4.1   3.6k
199  Pidilite Industries    4.2   3.6k

[200 rows x 3 columns]