In [ ]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
# pd.read_json('https://api.exchange ...')

In [4]:
#For my sql remember Lecture this at 8:00 minute after

In [ ]:
# !pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 2.8 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/11.9 MB 1.9 MB/s eta 0:00:06
     ---- ----------------------------------- 1.3/11.9 MB 1.9 MB/s eta 0:00:06
     ----- ---------------------------------- 1.6/11.9 MB 1.8 MB/s eta 0:00:06
     ------ --------------------------------- 1.8/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 1.6 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 1.5 MB/s eta 0:00:07
     -------- ------------------------------- 2.6/11.9 MB 1.5 MB/s eta 0:00:06
     --------- ------------------------------ 2.9/11.9 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.1/11.9 MB 1.5 MB/s eta 0:00:06
     ----------- ---------------------------- 3.4/11.9 MB 1.4 MB/s eta 0:00:06
     ------------ --------------------------- 3.7/11.9 MB 1.4 MB/s eta 0:00:06
     ------------- -------------------------- 3.9/11.9 MB 1.4 MB/s eta 0:00:06
     -------------- ------------------------- 4.2/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.5/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.7/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.7/11.9 MB 1.4 MB/s eta 0:00:06
     ---------------- ----------------------- 5.0/11.9 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 5.0/11.9 MB 1.3 MB/s eta 0:00:06
     ----------------- ---------------------- 5.2/11.9 MB 1.2 MB/s eta 0:00:06
     ----------------- ---------------------- 5.2/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 5.5/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.1 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.1 MB/s eta 0:00:06
     -------------------- ------------------- 6.0/11.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.3/11.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.3/11.9 MB 1.1 MB/s eta 0:00:06
     ---------------------- ----------------- 6.6/11.9 MB 1.1 MB/s eta 0:00:05
     ----------------------- ---------------- 6.8/11.9 MB 1.1 MB/s eta 0:00:05
     ----------------------- ---------------- 7.1/11.9 MB 1.1 MB/s eta 0:00:05
     ------------------------ --------------- 7.3/11.9 MB 1.1 MB/s eta 0:00:05
     ------------------------- -------------- 7.6/11.9 MB 1.1 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.1 MB/s eta 0:00:04
     ---------------------------- ----------- 8.4/11.9 MB 1.1 MB/s eta 0:00:04
     ----------------------------- ---------- 8.7/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 9.2/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 9.2/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 9.2/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.1 MB/s eta 0:00:03
     -------------------------------- ------- 9.7/11.9 MB 1.1 MB/s eta 0:00:03
     -------------------------------- ------- 9.7/11.9 MB 1.1 MB/s eta 0:00:03
     --------------------------------- ------ 10.0/11.9 MB 1.0 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.0 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.0 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.0 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.0 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.0 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.0 MB/s eta 0:00:02
     ----------------------------------- -- 11.0/11.9 MB 999.8 kB/s eta 0:00:01
     ------------------------------------ - 11.3/11.9 MB 999.5 kB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.0 MB/s  0:00:11
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=248038 sha256=26c310146f89b6f5b10cf816b37b3238505d0e84c99e6d354d1df284f0cf9f8a
  Stored in directory: c:\users\ramje\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import mysql.connector

In [ ]:
#conn=mysql.connector.connect(host='localhost',user='root', password='', database='world')

In [ ]:
#pd.read_sql_query("SELECT * FROM countrylanguage WHERE IsOfficial LIKE 'T' ", conn)

C:\Users\ramje\AppData\Local\Temp\ipykernel_27416\2074995819.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM countrylanguage WHERE IsOfficial LIKE 'T' ", conn)

    CountryCode   Language IsOfficial  Percentage
0           ABW      Dutch          T         5.3
1           AFG       Dari          T        32.1
2           AFG     Pashto          T        52.4
3           AIA    English          T         0.0
4           ALB  Albaniana          T        97.9
..          ...        ...        ...         ...
233         ZAF  Afrikaans          T        14.3
234         ZAF    English          T         8.5
235         ZAF      Xhosa          T        17.7
236         ZAF       Zulu          T        22.7
237         ZWE    English          T         2.2

[238 rows x 4 columns]